[masters]
35.197.170.207 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/v9/id_ed25519

[workers]
35.244.90.130 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/v9/id_ed25519
34.151.68.228 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/v9/id_ed25519
