# Generated by Django 6.0.1 on 2026-02-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_listing_category_image_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='owner',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
