# Generated by Django 6.0.1 on 2026-02-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comments_comment_listing_comments_comment_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watched_by', to='auctions.auction_listing'),
        ),
    ]
