# Generated by Django 6.0.1 on 2026-03-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auction_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction_Listing',
            new_name='Post_listing',
        ),
    ]
