# Generated by Django 6.0.1 on 2026-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing_bids_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category_image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='listing_image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
