# Generated by Django 6.0.1 on 2026-02-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listing_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='category_image_link',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='category',
            field=models.URLField(blank=True, null=True),
        ),
    ]
