# Generated by Django 6.0.1 on 2026-02-20 07:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_listing_winner_alter_auction_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_time',
            field=models.DateTimeField(default=datetime.date(2026, 2, 20)),
        ),
    ]
