# Generated by Django 6.0.1 on 2026-02-20 07:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bids_bid_listing_bids_bid_owner_bids_bid_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.date(2026, 2, 20)),
        ),
    ]
