# Generated by Django 6.0.1 on 2026-02-20 15:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bids_bid_time_alter_comments_comment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 15, 13, 39, 90881, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 15, 13, 39, 91380, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing')),
                ('fav_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
