# Generated by Django 6.0.1 on 2026-02-20 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bids_bid_time_alter_comments_comment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 16, 9, 37, 844766, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 16, 9, 37, 845267, tzinfo=datetime.timezone.utc)),
        ),
    ]
